Moive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:m_id>/comment/', views.comment_create, name='comment_create'),
    path('<int:m_id>/comment/<int:c_id>/delete', views.comment_delete, name='comment_delete'),
]

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=150)
    title_en = models.CharField(max_length=150)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=150)
    watch_grade = models.CharField(max_length=150)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.CharField(max_length=500)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Comment

# Create your views here.
def index(request):
    context = {
        'movies': Movie.objects.all(),
    }
    return render(request, 'index.html', context)


def create(request):
    if request.method == 'POST':
        movie = Movie.objects.create(
            title = request.POST.get('title'),
            title_en = request.POST.get('title-en'),
            audience = request.POST.get('audience'),
            open_date = request.POST.get('open-date'),
            genre = request.POST.get('genre'),
            watch_grade = request.POST.get('watch-grade'),
            score = request.POST.get('score'),
            poster_url = request.POST.get('poster-url'),
            description = request.POST.get('description')
        )
        return redirect('movies:index')
    else:
        return render(request, 'form.html')


def detail(request, id):
    context = {
        'movie': Movie.objects.get(id=id),
    }
    return render(request, 'detail.html', context)


def update(request, id):
    movie = Movie.objects.get(id=id)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.title_en = request.POST.get('title-en')
        movie.audience = request.POST.get('audience')
        movie.open_date = request.POST.get('open-date')
        movie.genre = request.POST.get('genre')
        movie.watch_grade = request.POST.get('watch-grade')
        movie.score = request.POST.get('score')
        movie.poster_url = request.POST.get('poster-url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:detail', id)
    else:
        context = {
            'movie': movie,
        }
        return render(request, 'form.html', context)


def delete(request, id):
    Movie.objects.get(id=id).delete()
    return redirect('movies:index')


def comment_create(request, m_id):
    # POST 방식
    Comment.objects.create(
        content = request.POST.get('content'),
        movie = Movie.objects.get(id=m_id),
    )
    return redirect('movies:detail', m_id)

def comment_delete(request, m_id, c_id):
    Comment.objects.get(id=c_id).delete()
    return redirect('movies:detail', m_id)

movies/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>pjt05-Movie</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Cute+Font|Gugi|Sunflower:300&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/e1e3095336.js" crossorigin="anonymous"></script>
  <style>
      body {
        background-image: url("{% static 'background.jpg' %}");
      }
      a {
        font-weight: bold;
        color: whitesmoke;
        text-decoration-line: none;
        text-decoration-color: whitesmoke;
      }
      
      .gugi {
        font-family: 'Gugi', cursive;
      }
      .cute {
        font-family: 'Cute Font', cursive;
        font-size: 120%;
      }
      .sun {
        font-family: 'Sunflower', sans-serif;
      }
  </style>
</head>
<body >
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light sun">
    <a class="navbar-brand" href="{% url 'movies:index' %}"><i class="fas fa-film"></i> 영화 사이트</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link text-light" href="{% url 'movies:create' %}"> 등록하기 <span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

movies/templates/detail.html
{% extends 'base.html' %}

{% block body %}
<h1 class="text-light text-center mt-4 gugi">영화 상세정보</h1>
<div class="container mt-3 shadow-lg p-0 mb-0 bg-white rounded">
  <div class="card mb-3 bg-light" style="max-width: 80;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="{{movie.poster_url}}" class="card-img" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-header gugi">
          <div class="row">
            <div class="col-8">
              <h2 class="card-title my-auto">{{movie.title}} ({{movie.title_en}})</h2>
            </div>
            <div class="col-4 text-right">
              <a href="{% url 'movies:update' movie.id %}" class="btn btn-secondary btn-lg" role="button" aria-pressed="true">수정</a>
              <a href="{% url 'movies:delete' movie.id %}" class="btn btn-danger btn-lg" role="button" aria-pressed="true">삭제</a>
            </div>
          </div>
        </div>
        <div class="card-body sun">
          <div class="row mb-3">
            <div class="col-2 text-right font-weight-bold">개봉일</div>
            <div class="col-9">{{movie.open_date}}</div>
          </div>
          <div class="row mb-3">
            <div class="col-2 text-right font-weight-bold">평점</div>
            <div class="col-9">
              <span class="badge badge-info">{{movie.score}}</span>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-2 text-right font-weight-bold">장르</div>
            <div class="col-9">{{movie.genre}}</div>
          </div>
          <div class="row mb-3">
            <div class="col-2 text-right font-weight-bold">관람등급</div>
            <div class="col-9">{{movie.watch_grade}}</div>
          </div>
          <div class="row mb-3">
            <div class="col-2 text-right font-weight-bold">누적관객</div>
            <div class="col-9">{{movie.audience}}명</div>
          </div>
          <div class="row mb-3">
            <div class="col-2 text-right font-weight-bold">영화 소개</div>
            <div class="col-9">{{movie.description}}</div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <ul class="list-group mb-5">
    <li class="list-group-item">
      <form action="{% url 'movies:comment_create' movie.id %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
          <div class="input-group-prepend my-2 my-sm-1">
            <label for="content">
              <span class="input-group-text sun">Reviews</span>
            </label>
          </div>
          <input type="text" class="form-control my-2 my-sm-1 sun" id="content" name="content" placeholder="한줄 감상평을 등록해주세요." >
          <button class="btn btn-primary my-0 my-sm-0 sun" type="submit">등록</button>
        </div>
      </form>
    </li>
      {% for comment in movie.comment_set.all %}
        <li class="list-group-item">
          <div class="row">
            <div class="col-1"></div>
            <div class="col-10 text-left cute">{{comment.content}}
              <div class="row">
                  <small class="form-text text-muted text-right mx-3">등록일: {{comment.created_at}}</small>
                  <a href="{% url 'movies:comment_delete' movie.id comment.id %}" class="btn btn-danger btn-sm" role="button" aria-pressed="true">DEL</a>
              </div>
            </div>
            <div class="col-1"></div>
          </div>
        </li>
      {% empty %}
        <li class="list-group-item text-center gugi"><h5>등록된 감상평이 없습니다.</h5></li>
      {% endfor %}
  </ul>
</div>
{% endblock %}

movies/templates/form.html
{% extends 'base.html' %}

{% block body %}
<div class="container mt-5 text-light font-weight-bold text-right">
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group row">
      <label for="title" class="col-sm-2 col-form-label">Title</label>
      <div class="col-sm-10">
        <input type="text" class="form-control rounded-pill" id="title" name="title" placeholder="제목" value="{{movie.title}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="title-en" class="col-sm-2 col-form-label">Title(English)</label>
      <div class="col-sm-10">
        <input type="text" class="form-control rounded-pill" id="title-en" name="title-en" placeholder="영문제목" value="{{movie.title_en}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="audience" class="col-sm-2 col-form-label">Audience</label>
      <div class="col-sm-10">
        <input type="number"" class="form-control rounded-pill" id="audience" name="audience" placeholder="누적관객수" value="{{movie.audience}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="open-date" class="col-sm-2 col-form-label">OpenDate</label>
      <div class="col-sm-10">
        <input type="date" class="form-control rounded-pill" id="open-date" name="open-date" value="{{movie.open_date|date:'Y-m-d'}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="genre" class="col-sm-2 col-form-label">Genre</label>
      <div class="col-sm-10">
        <input type="text" class="form-control rounded-pill" id="genre" name="genre" placeholder="장르" value="{{movie.genre}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="watch-grade" class="col-sm-2 col-form-label">WatchGrade</label>
      <div class="col-sm-10">
        <input type="text" class="form-control rounded-pill" id="watch-grade" name="watch-grade" placeholder="관람등급" value="{{movie.watch_grade}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="score" class="col-sm-2 col-form-label">Score</label>
      <div class="col-sm-10">
        <input type="number" class="form-control rounded-pill" id="score" name="score" placeholder="평점" step="0.01" value="{{movie.score}}">
      </div>
    </div>

    <div class="form-group row">
      <label for="poster-url" class="col-sm-2 col-form-label">PosterURL</label>
      <div class="col-sm-10">
        <input type="text" class="form-control rounded-pill" id="poster-url" name="poster-url" placeholder="포스터 주소" value="{{movie.poster_url}}">
      </div>
    </div>

    <div class="form-group row mb-5">
      <label for="description" class="col-sm-2 col-form-label">Description</label>
      <div class="col-sm-10">
        <textarea class="form-control rounded-lg" id="description" name="description" rows="3" placeholder="영화 소개">{{movie.description}}</textarea>
      </div>
    </div>

    <div class="form-group row text-center">
      <div class="col-sm-12">
        <input class="btn btn-dark btn-lg" type="submit" value="등록">
        <a href="{% url 'movies:index' %}" class="btn btn-danger btn-lg" role="button" aria-pressed="true">취소</a>
      </div>
    </div>
  </form>
</div>
{% endblock %}

movies/templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class="container mt-5">
  <h1 class="text-light text-center gugi">영화 목록</h1>
  <table class="table table-dark text-light mt-4 gugi">
    <thead class="text-center">
      <tr>
        <th scope="col">#</th>
        <th scope="col">TITLE - MOVIR RATING</th>
        <th scope="col">GENRE</th>
        <th scope="col">RELEASE DATE</th>
      </tr>
    </thead>
    <tbody>
      {% for movie in movies %}
        <tr>
          <th class="text-center" scope="row">{{movie.id}}</th>
          <td>
            <a href="{% url 'movies:detail' movie.id %}">
              {{movie.title}} ({{movie.title_en}}) - <span class="badge badge-info">{{movie.score}}</span>
            </a>
          </td>
          <td class="text-center">{{movie.genre}}</td>
          <td class="text-center">{{movie.open_date}}</td>
        </tr>
      {% empty %}
        <tr>
          <td><h3 class="text-light text-center">등록된 데이터가 없습니다.</h3></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}